#!/bin/bash
make
make main
chmod +x main
insmod ./mastermind.o
major_num=$(dmesg | tail -n 1 | cut -d' ' -f 5)
echo $major_num
mknod /dev/codemaker c $major_num 0
mknod /dev/codebreaker c $major_num 1
sudo ./main
rm /dev/codemaker
rm /dev/codebreaker
rmmod mastermind